
@startuml
hide empty description
skinparam LineBackgroundColor #black
skinparam ArrowColor #black
state "Map" as state1 {
state "Map2" as state3 {
state "Wait 20s" as state4
}
}
state "Final State" as state2
@enduml
