@startuml
hide empty description
skinparam ArrowColor #black
skinparam state {

    BackgroundColor<<aslParallel>> #whitesmoke

    BackgroundColor<<aslPass>> #whitesmoke
    FontColor<<aslPass>> automatic

    BackgroundColor<<aslSucceed>> #green
    FontColor<<aslSucceed>> automatic

    BackgroundColor<<aslWait>> #whitesmoke
    FontColor<<aslWait>> automatic
    BackgroundColor<<Compensate>> #orange
}
state "Final State" as state2<<aslSucceed>>
state "Parallel" as state1<<aslParallel>> {
state "Branch 1" as state1_1 {
state "Wait 20s" as state3<<aslWait>>
}
state "Branch 2" as state1_2 {
state "Pass" as state4<<aslPass>>
state "Wait 10s" as state5<<aslWait>>
}
}
[*] --> state1
state1 --> state2
state1 -[bold,#orange]-> state2
state2 --> [*]
state4 --> state5
@enduml
