
@startuml
hide empty description
skinparam LineBackgroundColor #black
skinparam ArrowColor #black
skinparam state {
    BackgroundColor<<aslFail>> #red
    FontColor<<aslFail>> #white

    BackgroundColor<<aslSucceed>> #green
    FontColor<<aslSucceed>> #white
}
state "Validate Input" as state1<<aslChoice>>
state "Get Customer Status" as state2<<aslTask>>
state "Do Fraud Check" as state3<<aslChoice>>
state "Notify New Order" as state4<<aslTask>>
state "Reserve Products" as state5<<aslMap>> {
state "Reserve Product" as state14<<aslTask>>
state "Choice" as state15<<aslChoice>>
state "Reservation Successful" as state16<<aslSucceed>>
state "Notify Delayed" as state17<<aslTask>>
state "Wait for availability" as state18<<aslWait>>
}
state "Notify Products Reserved" as state6<<aslTask>>
state "Initate Packaging and Shipping" as state7<<aslTask>>
state "Notify Successful Shipping" as state8<<aslTask>>
state "Notify Packaging and Shipping Failed" as state9<<aslTask>>
state "Notify Fraudulent Customer" as state10<<aslTask>>
state "Order Shipping Failed" as state11<<aslFail>>
state "Order Shipped Successfully" as state12<<aslSucceed>>
state "Notify Invalid Input" as state13<<aslTask>>
[*] --> state1
state1 --> state13
state1 --> state2
state2 --> state3
state3 --> state10
state3 --> state4
state4 --> state5
state5 --> state6
state6 --> state7
state7 --> state8
state7 -[bold,#orange]-> state9
state8 --> state12
state9 --> state11
state10 --> state11
state11 -[bold,#red]-> [*]
state12 --> [*]
state13 --> state11
state14 --> state15
state15 --> state17
state15 --> state16
state16 --> [*]
state17 --> state18
state18 --> state14
@enduml
